Repository mpi4py/mpi4py, pull requests merged in 2021-09, with the labels that each got.

#101 docs: clarify communicator split when using -m mpi4py.futures
  docs/source/usrman/mpi4py.futures.rst
Labels: documentation

#103 mpi4py.bench: Add pingpong command
  src/mpi4py/bench.py
  src/mpi4py/bench.pyi
  test/coverage.sh
Labels: enhancement

#110 mpi4py.futures: Fix potential threading deadlock
  demo/futures/test_futures.py
  src/mpi4py/futures/_lib.py
  src/mpi4py/futures/pool.py
Labels: bug
