Repository mpi4py/mpi4py, pull requests merged in 2022-10, with the labels that each got.

#261 type: Explicitly list `__all__` entries in stubs
  src/mpi4py/__init__.pyi
  src/mpi4py/futures/__init__.pyi
  src/mpi4py/typing.pyi
Labels: bug, typing

#262 Fix a few typos
  DESCRIPTION.rst
  demo/mpi-ref-v1/ex-2.16.py
  demo/mpi-ref-v1/ex-2.32.py
  demo/mpi-ref-v1/ex-2.34.py
  demo/mpi-ref-v1/ex-2.35.py
  demo/mpi-ref-v1/ex-3.09.py
  docs/source/mpi4py.futures.rst
  docs/source/overview.rst
  src/mpi4py/MPI/MPI.pyx
  src/mpi4py/util/dtlib.py
  src/python.c
  test/test_comm.py
  test/test_group.py
Labels: documentation

#263 type: Update after resolution of python/mypy#13627
  .github/workflows/ci.yml
  conf/requirements-type.txt
  tox.ini
Labels: typing

#265 test: Modernize testsuite
  .github/workflows/ci.yml
  conf/requirements-lint.txt
  demo/futures/test_futures.py
  demo/futures/test_service.py
  demo/reductions/test_reductions.py
  demo/test-run/run-script.py
  demo/test-run/test_run.py
  test/mpiunittest.py
  test/test_attributes.py
  test/test_cco_buf.py
  test/test_cco_nb_buf.py
  test/test_cco_ngh_obj.py
  test/test_cco_obj.py
  test/test_cco_obj_inter.py
  test/test_cco_pr_buf.py
  test/test_cffi.py
  test/test_comm.py
  test/test_comm_inter.py
  test/test_comm_topo.py
  test/test_ctypes.py
  test/test_datatype.py
  test/test_doc.py
  test/test_dynproc.py
  test/test_environ.py
  test/test_errhandler.py
  test/test_errorcode.py
  test/test_exceptions.py
  test/test_file.py
  test/test_grequest.py
  test/test_group.py
  test/test_info.py
  test/test_io.py
  test/test_memory.py
  test/test_mpiapi.py
  test/test_msgspec.py
  test/test_objmodel.py
  test/test_op.py
  test/test_p2p_buf.py
  test/test_p2p_buf_matched.py
  test/test_p2p_obj.py
  test/test_p2p_obj_matched.py
  test/test_pack.py
  test/test_pickle.py
  test/test_request.py
  test/test_rma_nb.py
  test/test_session.py
  test/test_spawn.py
  test/test_status.py
  test/test_subclass.py
  test/test_threads.py
  test/test_toplevel.py
  test/test_util_dtlib.py
  test/test_util_pkl5.py
  test/test_win.py
  tox.ini
Labels: test

#266 docs: Upgrade to Sphinx 5.2.3
  conf/requirements-docs.txt
  docs/source/conf.py
Labels: documentation

#270 test: Fix and extend pickle point-to-point tests
  test/test_p2p_obj.py
Labels: test

#272 build: Update for Intel MPI 2021.7.0 on Windows
  conf/mpiconfig.py
  conf/mpidistutils.py
  mpi.cfg
Labels: build
