Repository mpi4py/mpi4py, pull requests merged in 2023-02, with the labels that each got.

#313 Fix small typo in overview article in docs
  docs/source/overview.rst
Labels: documentation

#315 build: Update custom Cython script used with scikit-build+cmake
  .github/workflows/ci.yml
  conf/cythoncmd.py
  src/mpi4py/CMakeLists.txt
  test/test_package.py
  test/test_toplevel.py
Labels: build

#316 build: Update/simplify Cython script used to generate C sources
  conf/cyautodoc.py
  conf/cythoncmd.py
  conf/cythonize.py
  conf/cythonize.sh
  conf/mpidistutils.py
  src/mpi4py/CMakeLists.txt
Labels: refactor, build

#319 build: Suppress stderr while running lengthy MPI configure tests
  .github/workflows/ci.yml
  conf/mpidistutils.py
  setup.py
  tox.ini
Labels: enhancement, build
